#!/bin/bash    

# can run as:  
# bsub -q cmscaf1nd -oo /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/tmpcommand_muon_2.log  "source /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/tmpcommand_muon_2.sh"

cd /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter
eval `scramv1 runtime -sh`

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.98 1.02 --fixRatioRange   --sP etal1,ptl1  -P /u2/mciprian/TREES_13TeV/muon/signalSkim/ -F Friends /u2/mciprian/TREES_13TeV/muon/signalSkim/friends/tree_Friend_{cname}.root  -p 'W,W_lepeff_Up,W_lepeff_Dn,W_muscale_Up,W_muscale_Dn' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/WlepEffAndScaleSyst_nostack/eta_0p0_2p5/ --ratioDen W --ratioNums 'W_lepeff_Up,W_lepeff_Dn,W_muscale_Up,W_muscale_Dn' --plotmode nostack --noLegendRatioPlot --ratioYLabel 'var/nomi' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.0 2.0 --fixRatioRange   --sP etal1,ptl1  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data_fakes,data_fakes_slopeUp,data_fakes_slopeDn,data_fakes_normUp,data_fakes_normDn' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/fakesSyst_nostack_fixPR/eta_0p0_2p5/ --ratioDen data_fakes --ratioNums 'data_fakes_slopeUp,data_fakes_slopeDn,data_fakes_normUp,data_fakes_normDn' --plotmode nostack --noLegendRatioPlot --ratioYLabel 'var/nomi' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.9 1.1 --fixRatioRange   --sP ptl1 -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauDecaysW,Top,DiBosons' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/test1D_nofit_chMinus_allYields/  -A kinAccept negative 'LepGood1_charge<0' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.95 1.05 --fixRatioRange   --sP etal1,ptl1,ptl1__etal1  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'GenWTauDecaysW,TauDecaysW' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/compareTau_prefsrw_genw/ --ratioDen GenWTauDecaysW --ratioNums 'TauDecaysW' --plotmode nostack --noLegendRatioPlot --ratioYLabel 'prefsr/gen' "


#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-includes/mca-80X-wmunu-sig.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_reco_minimal.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP wplus_etal1,wplus_ptl1 -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'Wplus_long,Wplus_left,Wplus_right' -W 'puw2016_nTrueInt_36fb(nTrueInt)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/recoVar_minimalCuts_chPlus/ --plotmode nostack"


#echo "${command}" | bash

# command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-includes/mca-80X-wmunu-sig.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_reco_minimal.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP wminus_etal1,wminus_ptl1 -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'Wminus_long,Wminus_left,Wminus_right' -W 'puw2016_nTrueInt_36fb(nTrueInt)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/recoVar_minimalCuts_chMinus/ --plotmode nostack"


# echo "${command}" | bash


# command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP metPt,metPhi  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/PFmet_nofit_mT40smearMet20_plus/ -A kinAccept positive 'LepGood1_charge>0' -R mtl1pf40 mtl1pf40smearMet20 'mt_2(LepGood1_calPt,LepGood1_phi,getSmearedVar(met_pt,0.2,evt,isData,1),met_phi) >= 40.' "

# echo "${command}" | bash


#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP ptl1__etal1  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'W' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/PFmet_nofit_mT40smearMet10_minus/ -A kinAccept negative 'LepGood1_charge<0' -R mtl1pf40 mtl1pf40smearMet10 'mt_2(LepGood1_calPt,LepGood1_phi,getSmearedVar(met_pt,0.1,evt,isData,1),met_phi) >= 40.' "

# echo "${command}" | bash

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP ptl1,etal1  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/ptAndEta_mT40to100_nofit_minus/ -A kinAccept negative 'LepGood1_charge<0' -A kinAccept mtUp 'mt_2(met_pt,met_phi,LepGood1_calPt,LepGood1_phi) < 100' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8   --sP ptl1__etal1 -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees/friends/tree_Friend_{cname}.root  -p 'W' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/ptVsEta_W_metNominal_minus/ -A kinAccept positive 'LepGood1_charge<0'  "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP ptl1_large,etal1,ptl1_large__etal1 -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta) * _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/SKIMS_muons_latest/FRclosure_MarcFR_scaleQCD_mT30_plus/ -A kinAccept positive 'LepGood1_charge>0' -R mtl1pf40 mtl1pfMax30 'mt_2(met_pt,met_phi,ptMuFull(LepGood1_calPt,LepGood1_eta),LepGood1_phi) < 30' --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 --scaleSigToData --sp data_fakes "


#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP pfmt -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/SKIMS_muons_latest/mT_ptMax56_plus/ -A kinAccept positive 'LepGood1_charge>0' -X mtl1pf40 --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.6 1.1 --fixRatioRange   --sP ptl1_large,etal1,ptl1_large__etal1 -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data_fakes,data_fakes_jetPt40' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/SKIMS_muons_latest/FRcomparison_jetPt40_mt0to40_plus/ -A kinAccept positive 'LepGood1_charge>0' --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 --ratioDen data_fakes --ratioNums 'data_fakes_jetPt40' --plotmode nostack --ratioYLabel 'jetPt40/nomi' -R mtl1pf40 mt0to40 'mt_2(met_pt,met_phi,LepGood1_calPt,LepGood1_phi) < 40' "


#/eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/
#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.96 1.04 --fixRatioRange   --sP ptl1_26to56,etal1,ptl1_26to56__etal1 -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'W,W_muscale1Up,W_muscale1Dn,W_muscale0Up,W_muscale0Dn' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/checkMuScale/check_Wmuscale_NoPtBins_ptMin26_ptMax56_plus/ -A kinAccept positive 'LepGood1_charge>0' --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 --ratioDen W --ratioNums 'W_muscale1Up,W_muscale1Dn,W_muscale0Up,W_muscale0Dn' --plotmode nostack --ratioYLabel 'var./nomi' --noLegendRatioPlot "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP unrolled -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'Wp,Wm' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/testWnorm_eosNtpMarc/Wcharge_unrolled/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode nostack  --canvasSize 3000 750 --setTitleYoffset 0.32 "

command='python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam "#bf{CMS} #it{Preliminary}"  --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/mca_forMuonFR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/cuts_forMuonFR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/plots_forMuonFR.txt --noCms -j 8  --sP "ptl1,etal1,ptl1__etal1,isol1,muonId,awayJet_pt,awayJet_eta,mt,mt_jet_mu,mass_jet_mu,dphiLepAwayJet,detaLepAwayJet,dRLepAwayJet,iso03,dxy,dz,met_pt,nVert,miniRelIso" -P /eos/cms/store/cmst3/group/wmass/mciprian/TREE_4_WMASS_skimMuonFR_21Jan2020/  -F Friends /eos/cms/store/cmst3/group/wmass/mciprian/TREE_4_WMASS_skimMuonFR_21Jan2020/friends/tree_Friend_{cname}.root  -W "puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta)*_get_muonSF_selectionToTrigger(LepGood1_pdgId,LepGood1_calPt,LepGood1_eta,LepGood1_charge)*prefireJetsWeight(LepGood1_eta)" --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/plots/Wlike/TREE_4_WLIKE_MU/comparisons/checkFR_computationRegion_failIso/ --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 -p "data,Wptmu,TauDecaysWpt,QCD,DiBosons,Top,Zpt"  --allProcInLegend --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange --noLegendRatioPlot --n-column-legend 3 -A mu fail_muTightIso "LepGood1_relIso04 > 0.15" '

echo "${command}"
echo "${command}" | bash


