#!/bin/bash    

# can run as:  
# bsub -q cmscaf1nd -oo /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/tmpcommand_muon.log  "source /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/tmpcommand_muon.sh"

cd /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter
eval `scramv1 runtime -sh`

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.98 1.02 --fixRatioRange   --sP etal1,ptl1  -P /u2/mciprian/TREES_13TeV/muon/signalSkim/ -F Friends /u2/mciprian/TREES_13TeV/muon/signalSkim/friends/tree_Friend_{cname}.root  -p 'W,W_lepeff_Up,W_lepeff_Dn,W_muscale_Up,W_muscale_Dn' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/WlepEffAndScaleSyst_nostack/eta_0p0_2p5/ --ratioDen W --ratioNums 'W_lepeff_Up,W_lepeff_Dn,W_muscale_Up,W_muscale_Dn' --plotmode nostack --noLegendRatioPlot --ratioYLabel 'var/nomi' "


#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.75 1.25 --fixRatioRange   --sP etal1,ptl1,ptl1__etal1  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data_fakes,data_fakes_slopeUp,data_fakes_slopeDn' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/fakesSyst_norm_fixPR_changeOnlySlope/eta_0p0_2p5/ --ratioDen data_fakes --ratioNums 'data_fakes_slopeUp,data_fakes_slopeDn' --plotmode norm --noLegendRatioPlot --ratioYLabel 'var/nomi' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP unrolled,unrolled_pt  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta) * _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/unrolled_fitData_triggerChargeSF_L1prefire/  --canvasSize 3000 750 --setTitleYoffset 0.32 --fitData" # --noLegendRatioPlot

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP ptl1,etal1  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta) * _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_new/SKIMS_muons_latest/sigRegion_fitData_triggerChargeSF_L1prefire/  --fitData --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92" # --noLegendRatioPlot


#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.75 1.25 --fixRatioRange   --sP etal1,ptl1,ptl1__etal1  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data_fakes,data_fakes_slopeUp,data_fakes_slopeDn,data_fakes_normUp,data_fakes_normDn' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/fakesSyst_nostack_fixPR/eta_0p0_2p5/ --ratioDen data_fakes --ratioNums 'data_fakes_slopeUp,data_fakes_slopeDn,data_fakes_normUp,data_fakes_normDn' --plotmode nostack --noLegendRatioPlot --ratioYLabel 'var/nomi' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.9 1.1 --fixRatioRange   --sP ptl1 -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauDecaysW,Top,DiBosons' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/test1D_nofit_chPlus_allYields/ -A kinAccept positive 'LepGood1_charge>0' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.92 1.08 --fixRatioRange   --sP ptl1,etal1,ptl1__etal1 -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data_fakes,data_fakes_slopeUp,data_fakes_slopeDn' -W 'puw2016_nTrueInt_36fb(nTrueInt)*lepSF(LepGood1_pdgId,LepGood1_pt,LepGood1_eta,LepGood1_SF1,LepGood1_SF2,1)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/fakesSyst_nostack_fixPR_changeOffsetWithSlope/ --ratioDen data_fakes --ratioNums 'data_fakes_slopeUp,data_fakes_slopeDn' --plotmode nostack --noLegendRatioPlot --ratioYLabel 'var/nomi' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8   --sP ptl1,etal1,ptl1__etal1 -P /eos/cms/store/cmst3/group/wmass/mciprian/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_NOMT_V2/ -F Friends /eos/cms/store/cmst3/group/wmass/mciprian/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_NOMT_V2/friends/tree_Friend_{cname}.root  -p 'Wp,Wm' -W 'puw2016_nTrueInt_36fb(nTrueInt)*lepSF(LepGood1_pdgId,LepGood1_pt,LepGood1_eta,LepGood1_SF1,LepGood1_SF2,1)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_NOMT_V2/trashtest/  --plotmode nostack "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP ptl1,etal1 -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/ptAndEta_mT40to100_nofit_plus/ -A kinAccept positive 'LepGood1_charge>0' -A kinAccept mtUp 'mt_2(met_pt,met_phi,LepGood1_calPt,LepGood1_phi) < 100' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8   --sP ptl1__etal1 -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees/friends/tree_Friend_{cname}.root  -p 'W' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood1_SF1*LepGood1_SF2'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots/SKIMS_muons_latest/ptVsEta_W_metJecUp_minus/ -A kinAccept positive 'LepGood1_charge<0' -R mtl1pf40 mtJecUp 'mt_2(met_jecUp_pt,met_jecUp_phi,LepGood1_calPt,LepGood1_phi) > 40' "


#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.9 1.1 --fixRatioRange   --sP ptl1,etal1,ptl1__etal1 -P /eos/cms/store/cmst3/group/wmass/mciprian/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/ -F Friends /eos/cms/store/cmst3/group/wmass/mciprian/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/friends/tree_Friend_{cname}.root  -p 'W' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta) * _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/SKIMS_muons_latest/testMt_nofit_plus_noMt/ -A kinAccept positive 'LepGood1_charge>0' -X mtl1pf40 --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange   --sP pfmt -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,W,data_fakes,Z,TauTopVV' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/SKIMS_muons_latest/mT_ptMax56_minus/ -A kinAccept negative 'LepGood1_charge<0' -X mtl1pf40 --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 "

#/u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/
#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.98 1.02 --fixRatioRange   --sP ptl1_26to56,ptl1_26to56__etal1 -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/ -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/friends/tree_Friend_{cname}.root  -p 'W,W_muscale_Up' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/SKIMS_muons_latest/check_Wmuscale_ptMax60_plus/ -A kinAccept positive 'LepGood1_charge>0' --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 --ratioDen W --ratioNums 'W_muscale_Up' --plotmode nostack --ratioYLabel 'var./nomi'  -R ptMax56 ptMax60 'LepGood1_calPt < 60' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.97 1.03 --fixRatioRange   --sP ptl1_26to56,ptl1_26to56__etal1 -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/ -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/friends/tree_Friend_{cname}.root  -p 'W,W_muscale_Up,W_muscale_Dn' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/checkMuScale/check_Wmuscale_ptMin26_ptMax56_plus_ptVar0p004flatAlongEta/ -A kinAccept positive 'LepGood1_charge>0' --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 --ratioDen W --ratioNums 'W_muscale_Up,W_muscale_Dn' --plotmode nostack --ratioYLabel 'var./nomi'  "

#/eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/
#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8 --showRatio --maxRatioRange 0.96 1.04 --fixRatioRange   --sP ptl1_26to56,etal1,ptl1_26to56__etal1 -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'Z,Z_muscale0Up,Z_muscale0Dn' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/checkMuScale/check_Zmuscale_ptMin26_ptMax56_plus_testFunction/ -A kinAccept positive 'LepGood1_charge>0' --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 --ratioDen Z --ratioNums 'Z_muscale0Up,Z_muscale0Dn' --plotmode nostack --ratioYLabel 'var./nomi' --noLegendRatioPlot "


# -R mtl1pf40 mt0to40 'mt_2(met_pt,met_phi,LepGood1_calPt,LepGood1_phi) < 40'

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/awayJetPlot_mu.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8   --sP pfmt__awayJetPt,pfmt__nAwayJet -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'data,QCD' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/SKIMS_muons_latest/mT_awayJet_test/  --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92  "


# SF for muons by charge:
# _get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta) * _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)
#-A kinAccept mtUp 'mt_2(met_pt,met_phi,LepGood1_calPt,LepGood1_phi) < 100'

# /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP ptl1__etal1,ptl1,etal1 -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/trees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  -p 'Wp,Wm' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/testWnorm_eosNtpMarc/Wcharge_2D_and_projection/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode nostack "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP unrolled -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/ -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_14Feb2019/friends/tree_Friend_{cname}.root  -p 'Wp,Wm' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/testWnorm/Wcharge_unrolled/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode nostack  --canvasSize 3000 750 --setTitleYoffset 0.32 "


#-A kinAccept positive 'LepGood1_charge>0'
#/u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP etal1 -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/ -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/friends/tree_Friend_{cname}.root  -p 'Wnozpt,Wzpt,Wfsr' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/effectZptFSR_pt26to56_etaOnly/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode norm --showRatio --maxRatioRange 0.99 1.01 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wnozpt,Wfsr' --ratioYLabel 'X/Wzpt' --contentAxisTitle 'arbitrary units' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP ptl1_large__etal1,ptl1_large -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/ -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/friends/tree_Friend_{cname}.root  -p 'Wnozpt,Wzpt' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/effectZpt_pt26to56/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode norm --showRatio --maxRatioRange 0.95 1.10 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wnozpt' --ratioYLabel 'no-Zpt / Zpt' --contentAxisTitle 'arbitrary units' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP ptl1_26to56__etal1_coarse,ptl1_26to56_coarse -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/ -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/friends/tree_Friend_{cname}.root  -p 'Wfsr,Wzpt' -W 'puw2016_nTrueInt_36fb(nTrueInt)* LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newSF/effectFSR_pt26to56_etaPtAnalysisBinning/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode norm --showRatio --maxRatioRange 0.99 1.01 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wfsr' --ratioYLabel 'FSR / no-FSR' --contentAxisTitle 'arbitrary units' "

#quick test with electrons
# /u1/mciprian/trees/electron/TREES_WELE_19Feb2019
#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_forPlots.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_80X_xsec.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt   --noCms  -j 8  --sP ptl1large__etal1,ptl1_large,etal1_binFR -P /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/ -F Friends /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/friends/tree_Friend_{cname}.root  -p 'Wzpt,Wfsr' -W 'puw2016_nTrueInt_36fb(nTrueInt)*lepSF(LepGood1_pdgId,LepGood1_pt,LepGood1_eta,LepGood1_SF1,LepGood1_SF2,LepGood1_SF3)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/electronPlots/testNewFSR_pt30to56/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode norm --showRatio --maxRatioRange 0.95 1.10 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wfsr' --ratioYLabel 'fsr/nomi.' --contentAxisTitle 'arbitrary units' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_forPlots.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_80X_xsec.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt   --noCms  -j 8  --sP ptl1large__etal1,ptl1_large,etal1_binFR -P /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/ -F Friends /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/friends/tree_Friend_{cname}.root  -p 'Wnozpt,Wzpt' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_electronSF_TriggerAndID(LepGood1_pdgId,LepGood1_calPt,LepGood1_eta)*LepGood1_SF2*eleSF_L1Eff(LepGood1_pt,LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/electronPlots/effectZpt_pt30to56_newSF/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode norm --showRatio --maxRatioRange 0.95 1.10 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wnozpt' --ratioYLabel 'no-Zpt / Zpt' --contentAxisTitle 'arbitrary units';   python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_forPlots.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_80X_xsec.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt   --noCms  -j 8  --sP ptl1large__etal1,ptl1_large,etal1_binFR -P /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/ -F Friends /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/friends/tree_Friend_{cname}.root  -p 'Wfsr,Wzpt' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_electronSF_TriggerAndID(LepGood1_pdgId,LepGood1_calPt,LepGood1_eta)*LepGood1_SF2*eleSF_L1Eff(LepGood1_pt,LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/electronPlots/effectFSR_pt30to56_newSF/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode norm --showRatio --maxRatioRange 0.99 1.01 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wfsr' --ratioYLabel 'FSR / no-FSR' --contentAxisTitle 'arbitrary units' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_forPlots.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_80X_xsec.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt   --noCms  -j 8  --sP etal1_binFR -P /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/ -F Friends /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/friends/tree_Friend_{cname}.root  -p 'Wfsr,Wnozpt,Wzpt' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_electronSF_TriggerAndID(LepGood1_pdgId,LepGood1_calPt,LepGood1_eta)*LepGood1_SF2*eleSF_L1Eff(LepGood1_pt,LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/electronPlots/effectZptFSR_pt30to56_newSF_etaOnly/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode norm --showRatio --maxRatioRange 0.99 1.01 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wfsr,Wnozpt' --ratioYLabel 'X / Zpt' --contentAxisTitle 'arbitrary units' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_forPlots.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/alwaystrue.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt  --sP gen_ptl1_absetal1_dressed --noCms  -j 8  -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees/ -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees/friends/tree_Friend_{cname}.root  -p 'Wzpt,Wfsr' -W '1.'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/electronPlots/test_FSRxsec_genLevel/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --showRatio --maxRatioRange 0.98 1.02 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wfsr' --ratioYLabel 'FSR/nomi' --palette 55 --drawBox '0.0,2.4,26,56' --max-entries 100 "

# command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_testFSR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/alwaystrue.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/tmp_plots.txt   --noCms  -j 8  --sP gen_ptl1_absetal1_dressed_mu_coarse -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees// -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees//friends/tree_Friend_{cname}.root  -p 'Wfsr_mu,Wzpt_mu' -W '1'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/FSR_atGenLevel_muon/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --showRatio --maxRatioRange 0.85 1.15 --fixRatioRange --ratioDen Wzpt_mu --ratioNums 'Wfsr_mu' --ratioYLabel 'FSR / no-FSR' " 

# echo "${command}" | bash

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_testFSR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/alwaystrue.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/tmp_plots.txt   --noCms  -j 8  --sP gen_ptl1_absetal1_dressed_el_coarse -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees// -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees//friends/tree_Friend_{cname}.root  -p 'Wfsr_el,Wzpt_el' -W '1'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/FSR_atGenLevel_electron/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --showRatio --maxRatioRange 0.85 1.15 --fixRatioRange --ratioDen Wzpt_el --ratioNums 'Wfsr_el' --ratioYLabel 'FSR / no-FSR' " 

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_forPlots.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_80X_xsec.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt   --noCms  -j 8  --sP ptl1__etal1_binAnalysis,ptl1_binAnalysis -P /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/ -F Friends /u1/mciprian/trees/electron/TREES_WELE_19Feb2019/friends/tree_Friend_{cname}.root  -p 'Wfsr,Wzpt' -W 'puw2016_nTrueInt_36fb(nTrueInt)*_get_electronSF_TriggerAndID(LepGood1_pdgId,LepGood1_calPt,LepGood1_eta)*LepGood1_SF2*eleSF_L1Eff(LepGood1_pt,LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/electronPlots/testFSRnorm_newSF/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode nostack --showRatio --maxRatioRange 0.95 1.05 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wfsr' --ratioYLabel 'FSR / no-FSR' --contentAxisTitle 'arbitrary units' "

#echo "${command}" | bash

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_forTests.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP ptl1_26to56__etal1_coarse,ptl1_26to56_coarse -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/ -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019/friends/tree_Friend_{cname}.root  -p 'Wfsr,Wzpt' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/muonPlots_newFSR/testFSRnorm_newSF/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --plotmode nostack --showRatio --maxRatioRange 0.95 1.05 --fixRatioRange --ratioDen Wzpt --ratioNums 'Wfsr' --ratioYLabel 'FSR / no-FSR' --contentAxisTitle 'arbitrary units' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_testFSR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/cuts_wmu_xsec.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/test_plots.txt   --noCms  -j 8  --sP ptl1_26to56__etal1_coarse,ptl1_26to56_coarse -P /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019// -F Friends /u1/mciprian/trees/muon/TREES_1LEP_80X_V3_SIGSKIM_WMUNU_FULLSEL_13June2019//friends/tree_Friend_{cname}.root  -p 'Wfsr_mu,Wzpt_mu' -W 'puw2016_nTrueInt_36fb(nTrueInt)*LepGood_SF2[0]* _get_muonSF_selectionToTrigger(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta, LepGood1_charge)*prefireJetsWeight(LepGood1_eta)'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/FSR_atRecolevel_muon_FSRnormGenArea/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --showRatio --maxRatioRange 0.95 1.15 --fixRatioRange --ratioDen Wzpt_mu --ratioNums 'Wfsr_mu' --ratioYLabel 'FSR / no-FSR' --palette 55 --plotmode nostack " 

#echo "${command}" | bash

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-80X_testFSR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/alwaystrue.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/tmp_plots.txt   --noCms  -j 8  --sP gen_ptl1_absetal1_dressed_el_coarse -P /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees// -F Friends /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees//friends/tree_Friend_{cname}.root  -p 'Wfsr_el,Wzpt_el' -W '1'  --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/distribution/FSR_atGenLevel_electron_genBinAnalysis/  --n-column-legend 2 --setLegendCoordinates 0.2,0.78,0.9,0.92 --showRatio --maxRatioRange 0.95 1.15 --fixRatioRange --ratioDen Wzpt_el --ratioNums 'Wfsr_el' --ratioYLabel 'FSR / no-FSR' --palette 55 " 

# /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/
# /eos/cms/store/cmst3/group/wmass/w-helicity-13TeV/ntuplesRecoil/TREES_SIGNAL_1l_recoil_fullTrees/
#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-includes/mca-80X-wmunu-sigInclCharge_gen_eta_pt_4xsec_withUnbinnedQCDscales.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/alwaystrue.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/tmp_plots.txt  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  --sP gen_ptl1_absetal1_dressed_binAna  --noCms  -j 8 --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/test/xsection_genAbsEtaPt_dressed_mu_binningAnalysis_yields/ -W '1' "

#command="python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam '#bf{CMS} #it{Preliminary}' --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_mu/mca-includes/mca-80X-wmunu-sigInclCharge_gen_eta_pt_4xsec.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/alwaystrue.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/w-helicity-13TeV/wmass_e/tmp_plots.txt  -P /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/ -F Friends /afs/cern.ch/work/m/mdunser/public/wmassTrees/SKIMS_muons_latest/friends/tree_Friend_{cname}.root  --sP gen_ptl1_absetal1_dressed_binAna  --noCms  -j 8 --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/test/xsection_genAbsEtaPt_dressed_mu_binningAnalysis_WptWeights_allQCDscales_yields/ -W 'dyptWeight(pt_2(GenLepDressed_pt[0],GenLepDressed_phi[0],GenPromptNu_pt[0],GenPromptNu_phi[0]),0)' "

#command='python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam "#bf{CMS} #it{Preliminary}"  --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/mca_forMuonFR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/cuts_forMuonFR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/plots_forMuonFR.txt --noCms -j 8  --sP "ptl1,etal1,ptl1__etal1,isol1,muonId,awayJet_pt,awayJet_eta,mt,mt_jet_mu,mass_jet_mu,dphiLepAwayJet,detaLepAwayJet,dRLepAwayJet,iso03,dxy,dz,met_pt,nVert,miniRelIso" -P /eos/cms/store/cmst3/group/wmass/mciprian/TREE_4_WMASS_skimMuonFR_21Jan2020/  -F Friends /eos/cms/store/cmst3/group/wmass/mciprian/TREE_4_WMASS_skimMuonFR_21Jan2020/friends/tree_Friend_{cname}.root  -W "puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta)*_get_muonSF_selectionToTrigger(LepGood1_pdgId,LepGood1_calPt,LepGood1_eta,LepGood1_charge)*prefireJetsWeight(LepGood1_eta)" --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/plots/Wlike/TREE_4_WLIKE_MU/comparisons/checkFR_computationRegion_denominator/ --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 -p "data,Wptmu,TauDecaysWpt,QCD,DiBosons,Top,Zpt"  --allProcInLegend --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange --noLegendRatioPlot --n-column-legend 3'



#command='python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam "#bf{CMS} #it{Preliminary}"  --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/mca_forMuonFR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/cuts_forMuonFR.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wmass_mu/plots_forMuonFR.txt --noCms -j 8  --sP "ptl1,etal1" -P /eos/cms/store/cmst3/group/wmass/mciprian/TREE_4_WMASS_skimMuonFR_21Jan2020/  -F Friends /eos/cms/store/cmst3/group/wmass/mciprian/TREE_4_WMASS_skimMuonFR_21Jan2020/friends/tree_Friend_{cname}.root  -W "puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta)*_get_muonSF_selectionToTrigger(LepGood1_pdgId,LepGood1_calPt,LepGood1_eta,LepGood1_charge)*prefireJetsWeight(LepGood1_eta)" --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/plots/Wlike/TREE_4_WLIKE_MU/comparisons/checkFR_computationRegion_denominator_Wshapes/ --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 -p "W,Wpt"  --allProcInLegend --showRatio --maxRatioRange 0.8 1.2 --fixRatioRange --noLegendRatioPlot --ratioNums W --ratioDen Wpt --ratioYLabel "W/Wpt" --plotmode nostack '

#command='python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam "#bf{CMS} #it{Preliminary}" --legendWidth 0.25 --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wlike_mu/mca-80X_zmm.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wlike_mu/cuts_zmm.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wlike_mu/plots_zmm.txt --noCms -j 8 --sP "etal1plus,ptl1plus,etaBothLep,ptBothLep,zmass,zmassLogy,mt_wlike" -P /eos/cms/store/cmst3/group/wmass/w-mass-13TeV/ntuples/SKIM_2LEP_wlike_mu_V1/ -F Friends /eos/cms/store/cmst3/group/wmass/w-mass-13TeV/ntuples/SKIM_2LEP_wlike_mu_V1/friends/tree_Friend_{cname}.root -W "puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId, LepGood1_calPt, LepGood1_eta) * _get_muonSF_recoToSelection(LepGood2_pdgId, LepGood2_calPt, LepGood2_eta)*prefireJetsWeight_2l(LepGood1_eta,LepGood2_eta)" --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/CMSSW_8_0_25/src/CMGTools/WMass/python/plotter/plots/Wlike/TREE_4_WLIKE_MU/comparisons/chPlus_oddEvts_withPrefire_trigSFonlyZ__1ifBothLepMatchTrig_elseOnPlusLepIfMatchElseOther_addTkMuTrigger_testWlikeAnalysis_mt45_compareFakesPredictions_addFRpol2/ --n-column-legend 2 --setLegendCoordinates 0.3,0.78,0.9,0.92 -p data_fakes,data_fakes_v2,data_fakes_v3,data_fakes_v4,data_fakes_v5 -A kinAccept plus "isOddEvent(evt)" -A kinAccept mt_wlike "mt_wlike(LepGood1_calPt,LepGood1_phi,LepGood1_charge,LepGood2_calPt,LepGood2_phi,LepGood2_charge,met_pt,met_phi,evt) > 45.0" --allProcInLegend --noLegendRatioPlot --showRatio --maxRatioRange 0.1 1.01 --fixRatioRange --ratioNums data_fakes_v2,data_fakes_v3,data_fakes_v4,data_fakes_v5 --ratioDen data_fakes --plotmode nostack --ratioYLabel "X/nomi" '

command='python /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/mcPlots.py -f -l 35.9 --s2v --tree treeProducerWMass --obj tree --lspam "#bf{CMS} #it{Preliminary}" --legendFontSize 0.05 /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wlike_mu/tests/mca-94X_zmm.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wlike_mu/tests/cuts_zmm.txt /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/w-mass-13TeV/wlike_mu/tests/plots_zmm.txt --noCms -j 8 --sP "pt,eta,pt_eta,zpt,mt_wlike,zmass,nJetClean,jetCleanEta1,jetCleanPt1,jetCleanEta2,jetCleanPt2" -P /afs/cern.ch/work/e/emanuele/TREES/SKIM_2LEP_wlike_mu_V2/ -F Friends /afs/cern.ch/work/e/emanuele/TREES/SKIM_2LEP_wlike_mu_V2/friends/tree_Friend_{cname}.root -W "puw2016_nTrueInt_36fb(nTrueInt)*_get_muonSF_recoToSelection(LepGood1_pdgId,LepGood1_kalPt,LepGood1_eta)*_get_muonSF_recoToSelection(LepGood2_pdgId,LepGood2_kalPt,LepGood2_eta)*prefireJetsWeight(returnChargeVal(LepGood1_eta,LepGood1_charge,LepGood2_eta,LepGood2_charge,evt))" --pdir /afs/cern.ch/work/m/mciprian/w_mass_analysis/heppy/rel_slc7/CMSSW_9_4_12/src/CMGTools/WMass/python/plotter/plots/Wlike/TREE_4_WLIKE_MU/testToDelete/ --n-column-legend 2 --setLegendCoordinates 0.2,0.77,0.9,0.92 -p "data,Z,data_fakes,Top2l,VV" --allProcInLegend --noLegendRatioPlot --showRatio --maxRatioRange 0.9 1.1 --fixRatioRange -A twolep evenEvents "isEvenEvent(evt)" -A twolep mt_wlike "mt_wlike(LepGood1_kalPt,LepGood1_phi,LepGood1_charge,LepGood2_kalPt,LepGood2_phi,LepGood2_charge,met_pt,met_phi,evt) > 45" --max-entries 100 '

echo "${command}" 
echo "${command}" | bash


